version: '3.9'

services:
  web:
    build: .
    command: gunicorn src.config.wsgi:application --bind 0.0.0.0:${PORT:-8000} --workers 3 --timeout 120
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
