version: '3.9'
services:
  web:
    build: .
    command: gunicorn src.config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: savannah_db
    restart: always
    environment:
      POSTGRES_USER: savannah
      POSTGRES_PASSWORD: savannah_user
      POSTGRES_DB: savannah_db
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: