# Generated by Django 5.2.6 on 2025-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
