# Generated by Django 5.2.6 on 2025-09-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_auth0_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth0_id',
        ),
    ]
